name: a3-massive-muscles-timer-ci

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 720
    strategy:
      fail-fast: false
      matrix:
        node: [ '10', '12', '14' ]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1.4.4
        with:
          node-version: ${{ matrix.node }}
      - name: setup test environment
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install chromium-chromedriver
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          npm install selenium-webdriver
      - name: run timer test
        run: |
          node test/frontend/timer.js
